version: '3.8'
services:
  opensearch:
    image: opensearchproject/opensearch:2.5.0 
    container_name: opensearch
    environment:
      - discovery.type=single-node      
      - http.port=9200
      # - plugins.security.disabled=true
    volumes:
      - opensearch-local-data:/usr/share/opensearch/data      
    ports:
      - 9200:9200    
      - 9600:9600      
    networks:
      - local

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.5.0 # Make sure the version of opensearch-dashboards matches the version of opensearch installed on other nodes
    container_name: opensearch-dashboards
    ports: 
      - target: 5601
        published: 5601
    # expose:
    #   - "5601" # Expose port 5601 for web access to OpenSearch Dashboards
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]' # Define the OpenSearch nodes that OpenSearch Dashboards will query
    networks:
      - local

  redis:
    image: redis:latest
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis-local-data:/data
    networks:
      - local

  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - 9000:9000
      - 9001:9001
    volumes:
      - minio-local-data:/data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["server", "/data", "--console-address", ":9001"]
    networks:
      - local  

  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres-local-data:/var/lib/postgresql/data
    env_file: ./postgres.env    
    networks:
      - local

volumes:
  opensearch-local-data:
    driver: local
  redis-local-data:
    driver: local
  minio-local-data:
    driver: local  
  postgres-local-data:
    driver: local

networks:
  local:
    driver: bridge