apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydebian
  labels:
    app: mydebian
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mydebian
  template:
    metadata:
      labels:
        app: mydebian
    spec:
      containers:
        - name: mydebian
          image: 192.168.122.1:5000/mydebian:v1
          imagePullPolicy: Always
      imagePullSecrets:
        - name: mydockercredentials
