version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: tsemach/get-started:part1
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
      restart_policy:
        # condition: on-failure
        condition: no
    ports:
      - "80:80"
    networks:
      - webnet
networks:
  webnet:
