version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: hello-world
    container_name: web
    deploy:
      replicas: 10
      resources:
        limits:
          cpus: "1.0"
          memory: 4G
    ports:
      - "8081:8081"
    networks:
      - webnet
networks:
  webnet:
