version: '3.8'

services:
  mongodb:
    image: mongo
    # restart: always
    environment:
      MONGO_INITDB_DATABASE: paragon
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:      
      - mongodb:/data/db
    networks:
      - mongodb

  mongo-express:
    image: mongo-express
    # restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_URL: mongodb://admin:admin@mongodb:27017/
    networks:
      - mongodb

volumes:
  mongodb:
    driver: local

networks:
  mongodb: