version: '3.0'

services:

  registry:
    container_name: mysql    
    image: mysql/mysql-server
    environment:
      MYSQL_DATABASE: 'db'      
      MYSQL_USER: 'mysql'      
      MYSQL_PASSWORD: 'mysql'      
      MYSQL_ROOT_PASSWORD: 'mysql'
    ports:
      - 3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: {}
